services:
  php:
    container_name: meu_php
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # 8080 é o Host, 80 é o porta no docker
    depends_on:
      - mysql

  mysql:
    container_name: meu_servidor_mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minha_app
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes: 
  mysql-data: