name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # executa apenas quando fizer push na branch main
  workflow_dispatch: # permite rodar manualmente

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # Faz login no DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Configura o buildx para builds mais modernos
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Faz build e push da imagem
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/biblioteca_php_mysql:latest